[features]
seeds = false
[programs.devnet]
magic_hat = "9BA5zgC9wQ3k7ty2Xkpif31Xu4ojbREBettAN3Hg44Bp"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://metaplex.devnet.rpcpool.com/"
wallet = "/home/abstracted/solana-wallet/dev1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
